name: Publish Docs on GitHub Pages
on: [ 'workflow_dispatch' ]
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'


      - name: Grant execute permission to gradlew
        run: chmod +x gradlew


      - name: Build project and generate docs with Dokka
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build dokkaHtml


      - name: Move docs to gh-pages
        run: |
          mkdir gh-pages
          mv README.md gh-pages/android/README.md
          mv glove-android/build/dokka/html/* gh-pages/
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: gh-pages